---
- name: install apache dependencies
  ansible.builtin.package:
    name: "{{ apache_const[ansible_os_family]['dependencies'] }}"
    state: present
    update_cache: true

- name: install apache packages
  ansible.builtin.package:
    name: "{{ apache_const[ansible_os_family]['packages'] }}"
    state: present
    update_cache: true