---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
      when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    merge:
      # Apache
      apache:
        enabled: true
      # Apache -> install
      apache_install:
        enabled: true
      # Apache -> config -> apache.conf
      apache_conf:
        enabled: true
        backup: true
      # Apache -> config -> modules
      apache_modules:
        enabled: true
        mods_enabled: [rewrite]
        mods_disabled: []
      # Apache -> config -> {virtualhost}.conf
      apache_virtualhost:
      # Apache -> config -> delete default virtual_host
        default_conf:
          enabled: true
          state: "absent"
      # Apache -> config -> add new virtual_host
        new_conf:
          enabled: true
          file: "new.conf"
          state: "present"
          src: "apache__virtualhost.j2"
          backup: false
          vars:
            ip: "*"
            port: "80"
            ServerName: "www.example.com"
            ServerAdmin: "webmaster@localhost"
            DocumentRoot: "/var/www/html"
            ErrorLog: "/var/log/{{ apache_const[ansible_os_family]['service_name'] }}/error.log"
            CustomLog: "/var/log/{{ apache_const[ansible_os_family]['service_name'] }}/access.log combined"
            SSLEngine: ""

  tasks:
    - name: role darexsu.apache
      include_role:
        name: darexsu.apache
