---
- name: Converge
  hosts: all
 
  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
      when: lookup('env', 'ANSIBLE_COMMAND') | length > 0
  
  vars:
    merge:
# apache ┄┄┄┄┄┄┄┄┄┄┄┄┄
      apache:
        enabled: true
    # ┏┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄         install apache
      apache_install:
        enabled: true
    # ┏┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄         configure apache.conf
      apache_conf:
        enabled: true
        backup: true
    # ┏┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄         virtual_host section
      apache_virtualhost:
      # ┏┄┄┄┄┄┄┄┄┄┄┄┄┄         delete default virtual_host
        default_conf:
          enabled: true
          state: "absent"
      # ┏┄┄┄┄┄┄┄┄┄┄┄┄┄         add new virtual_host
        new_conf:
          enabled: true    
          file: "new.conf"
          state: "present"
          src: "apache__virtualhost.j2"
          backup: false
          vars:
            ip: "*"
            port: "80"
            ServerName: "www.example.com"
            ServerAdmin: "webmaster@localhost"
            DocumentRoot: "/var/www/html"
            ErrorLog: "/var/log/{{ apache_const[ansible_os_family]['service_name'] }}/error.log"
            CustomLog: "/var/log/{{ apache_const[ansible_os_family]['service_name'] }}/access.log combined"
            SSLEngine: ""
            SSLCertificateFile:	""
            SSLCertificateKeyFile: ""
  
  tasks:
  - name: role darexsu.apache
    include_role: 
      name: darexsu.apache